version: "3.7"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment: 
      - MONGO_INITDB_ROOT_DATABASE=dally-dose
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
    ports: 
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes: 
  mongodb_data_container: