version: "3.8"

services:
  bot:
    build: ./vote
    command: npm run dev:bot
    depends_on: 
      - "postgres"

  fetch:
    build: ./scripts/fetch
    command: npm run dev:fetch-tweets
    depends_on: 
      - "postgres"

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: 
      - POSTGRES_DB: dally-dose
    volumes: 
      - "db-data:/var/lib/postgresql/data"