version: "3.7"

services:
  bot:
    build: .
    command: npm run dev:bot
    depends_on: 
      - "postgres"

  fetch:
    build: .
    command: npm run dev:fetch-tweets
    depends_on: 
      - "postgres"

  postgres:
    image: postgres:alpine
    volumes: 
      - "db-data:/home/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dally-dose

volumes: 
  db-data: