version: '3.4'

services:
  dally-dose:
    image: dally-dose
    build: .
    links:
      - db
    environment:
      NODE_ENV: development
    volumes:
      - "./:/usr/src/app"
    ports:
      - 3000
      - 9229:9229
    command: ts-node --inspect=0.0.0.0:9229 index.js

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .vscode/mysql-db:/var/lib/mysql
    env_file:
      - .env

