version: '3.4'

services:
  dally-dose:
    image: dally-dose
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    command: ts-node --inspect=0.0.0.0:9229 index.js