version: "3.4"

services:
  dally-dose:
    image: dally-dose
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - "mongo:mongo"
    environment:
      NODE_ENV: development
    volumes:
      - "./:/usr/src/app"
    ports:
      - 3000
      - 9229:9229
    command: npm run start-barebone -- --inspect=0.0.0.0:9229

  mongo:
    image: mongo:latest
    env_file: .env
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.infra/db:/data/db
