name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: daily
          MONGO_INITDB_ROOT_PASSWORD: watori

    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2.1.3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-deps-${{ hashFiles('package-lock.json') }}

      - name: Migration Test
        run: |
          npm ci
          npm run lint
          npm run build
          npm run db:purge
        env:
          DB_HOST: mongodb
          DB_PORT: ${{ job.services.mongodb.ports[27017] }}
          DB_NAME: dailywatori
          DB_USERNAME: ${{ job.services.mongodb.env[MONGO_INITDB_ROOT_USERNAME] }}
          DB_PASSWORD: ${{ job.services.mongodb.env[MONGO_INITDB_ROOT_PASSWORD] }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm ci
          npm run lint
          npm run build
          npm run release
